import type { Metadata } from 'next';
import './globals.css';

// Redux
import { Provider } from '@/redux/provider';

export const metadata: Metadata = {
  title: 'Shadow Net Admin Panel',
  description: 'Generated by Shadow Net Admin Panel',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
