import { BADGE_VARIANTS, STATUS } from './enums';

export const SHADOWNET_USER = 'shadownet_user';
export const SHADOWNET_TOKEN = 'shadownet_token';

export const statusVariant = {
  [STATUS.COMPLETE]: BADGE_VARIANTS.SUCCESS,
  [STATUS.INREVIEW]: BADGE_VARIANTS.NORMAL,
  [STATUS.PENDING]: BADGE_VARIANTS.WARNING,
  [STATUS.PENDINGINVITE]: BADGE_VARIANTS.NORMAL,
  [STATUS.ACTIONREQUIRED]: BADGE_VARIANTS.DANGER,
  [STATUS.PENDINGAPPROVAL]: BADGE_VARIANTS.SECONDARY,
  [STATUS.INACTIVE]: BADGE_VARIANTS.DANGER,
  [STATUS.ACTIVE]: BADGE_VARIANTS.SUCCESS,
  [STATUS.PAUSED]: BADGE_VARIANTS.WARNING,
  [STATUS.DRAFT]: BADGE_VARIANTS.DISABLED,
  [STATUS.ERROR]: BADGE_VARIANTS.DANGER,
  [STATUS.ERRORBANKCONNECTION]: BADGE_VARIANTS.DANGER,
};
